# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebScraper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Material', '~> 2.16.4'
  pod 'Alamofire', '~> 4.7.3'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'SideMenu'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'JGProgressHUD'
  # Pods for WebScraper

end
